<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #ffffff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        header {
            text-align: center;
            background-color: navy;
            color: #fff;
            padding: 10px;
            margin-bottom: 20px;
        }

        section {
            margin-bottom: 30px;
        }

        h1, h2 {
            color: navy;
        }

        .chart-container {
            display: flex;
            justify-content: space-around;
            flex-wrap: wrap;
        }

        #container1 {
            height: 400px;
        }

        .highcharts-figure,
        .highcharts-data-table table {
            min-width: 320px;
            max-width: 500px;
            margin: 1em auto;
        }

        .highcharts-data-table table {
            font-family: Verdana, sans-serif;
            border-collapse: collapse;
            border: 1px solid #ebebeb;
            margin: 10px auto;
            text-align: center;
            width: 100%;
            max-width: 500px;
        }

        .highcharts-data-table caption {
            padding: 1em 0;
            font-size: 1.2em;
            color: #555;
        }

        .highcharts-data-table th {
            font-weight: 600;
            padding: 0.5em;
        }

        .highcharts-data-table td,
        .highcharts-data-table th,
        .highcharts-data-table caption {
            padding: 0.5em;
        }

        .highcharts-data-table thead tr,
        .highcharts-data-table tr:nth-child(even) {
            background: #f8f8f8;
        }

        .highcharts-data-table tr:hover {
            background: #f1f7ff;
        }
    </style>
    <title>Scheme-wise Non-Tax Revenue Report</title>
</head>

<body>
    <div class="container">
        <header>
            <h1>Report-Analysis</h1>
        </header>
        
        
        <section id="introduction">
        <a href="home.php" class="button" style="top: 85px;float:right;"><button>Homepage</button></a>
            <h2>Introduction</h2>
            <p>Scheme-wise non-tax revenue refers to the income generated by the government through various schemes, programs, and activities that are not derived from taxes imposed on individuals or businesses. Non-tax revenue plays a crucial role in financing government operations, as it diversifies the sources of income and reduces dependency on taxation.</p>
        </section>

        <section id="charts">
            <h2>Pie Chart</h2>
            <div class="chart-container">
                <figure class="highcharts-figure">
                    <div id="container1"></div>
                    <p class="highcharts-description">
                        Pie chart showing  the department wise revenue collected. Changes as per the data in the database.
                    </p>
                </figure>
            </div>
        </section>

        <section id="analysis">
            <h2>Analysis</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </section>
    </div>

    <script>
        // Database configuration
        var data = <?php
            $servername = "localhost";
            $username = "root";
            $password = "";
            $dbname = "non_tax_revenue";

            $conn = new mysqli($servername, $username, $password, $dbname);

            if ($conn->connect_error) {
                die("Connection failed: " . $conn->connect_error);
            }

            $query = "SELECT * FROM departments";
            $getdata = $conn->query($query);

            $data = array();

            if ($getdata->num_rows > 0) {
                while ($row = $getdata->fetch_object()) {
                    $data[] = array('name' => $row->name, 'y' => floatval($row->amount_collected));
                }
            } else {
                $data[] = array('name' => 'No data available', 'y' => 0);
            }

            echo json_encode($data);
            ?>;
        
        // Highcharts initialization
        Highcharts.chart('container1', {
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: 0,
                plotShadow: false
            },
            title: {
                text: 'Department<br>wise<br>Amount<br>collected',
                align: 'center',
                verticalAlign: 'middle',
                y: 60
            },
            tooltip: {
                pointFormat: '{series.name}: <b>Rs {point.y:.2f}</b>'
            },
            accessibility: {
                point: {
                    valueSuffix: '%'
                }
            },
            plotOptions: {
                pie: {
                    dataLabels: {
                        enabled: true,
                        distance: -50,
                        style: {
                            fontWeight: 'bold',
                            color: 'white'
                        }
                    },
                    startAngle: -90,
                    endAngle: 90,
                    center: ['50%', '75%'],
                    size: '110%'
                }
            },
            series: [{
                type: 'pie',
                name: 'Amount Collected',
                innerSize: '50%',
                data: data
            }]
        });
    </script>
</body>

</html>
